### ISSUE TITLE
Cant install mythil

### ISSUE THREAD

**Issue by Lokizzle** [ConsenSysDiligence/mythril#1693]
Installation is failing.

```
/test# pip3 install mythril
Collecting mythril
  Downloading mythril-0.23.10.tar.gz (4.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 6.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: MarkupSafe<2.1.0 in /usr/lib/python3/dist-packages (from mythril) (2.0.1)
Collecting asn1crypto>=0.22.0
  Using cached asn1crypto-1.5.1-py2.py3-none-any.whl (105 kB)
Collecting blake2b-py
  Using cached blake2b_py-0.1.3.tar.gz (14 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Checking for Rust toolchain....
      Running `maturin pep517 write-dist-info --metadata-directory /tmp/pip-modern-metadata-ot3kswga --interpreter /usr/bin/python3`
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-u3th1ipr/overlay/local/lib/python3.10/dist-packages/maturin/__init__.py", line 174, in prepare_metadata_for_build_wheel
          output = subprocess.check_output(command)
        File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/usr/lib/python3.10/subprocess.py", line 501, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'maturin'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

**Comment by norhh** [comment]
Hi @Lokizzle, try using python 3.9, for some reason some external libraries that mythril uses does not support python 3.10

**Comment by SaifAtom** [comment]
still have the same problem even after switching to python3.9 also tried changing rust to nightly version and it did not work

**Comment by norhh** [comment]
Hi @SaifAtom , try using the docker container.
