### ISSUE TITLE
Crash without internet

### ISSUE THREAD

**Issue by gsalzer** [ConsenSysDiligence/mythril#1702]
## Description

Mythril throws an exception when started without internet connection, apparently because it tries to load the list of installable solc compilers proactively, even when no compiler download will be needed.

## How to Reproduce

Turn off the internet connection (like the Wifi) and start Mythril. 

```console
$ myth analyze solidity_examples/etherstore.sol
Traceback (most recent call last):
  File "/home/mythril/venv/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/mythril/venv/lib/python3.9/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mythril/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/mythril/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/mythril/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/mythril/venv/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/home/mythril/venv/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fbfba1de490>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mythril/venv/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/mythril/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/mythril/venv/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='solc-bin.ethereum.org', port=443): Max retries exceeded with url: /linux-amd64/list.json (Caused by NewConnectionErr
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mythril/venv/bin/myth", line 33, in <module>
    sys.exit(load_entry_point('mythril==0.23.8', 'console_scripts', 'myth')())
  File "/homehril/venv/bin/myth", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/mythril/venv/lib/python3.9/site-packages/mythril/__init__.py", line 8, in <module>
    from mythril.plugin.loader import MythrilPluginLoader
  File "/home/mythril/venv/lib/python3.9/site-packages/mythril/plugin/__init__.py", line 1, in <module>
    from mythril.plugin.interface import MythrilPlugin, MythrilCLIPlugin
  File "/home/mythril/venv/lib/python3.9/site-packages/mythril/plugin/interface.py", line 2, in <module>
    from mythril.laser.plugin.builder import PluginBuilder as LaserPluginBuilder
  File "/home/mythril/venv/lib/python3.9/site-packages/mythril/laser/plugin/builder.py", line 1, in <module>
    from mythril.laser.plugin.interface import LaserPlugin
  File "/home/mythril/venv/lib/python3.9/site-packages/mythril/laser/plugin/interface.py", line 1, in <module>
    from mythril.laser.ethereum.svm import LaserEVM
  File "/home/mythril/venv/lib/python3.9/site-packages/mythril/laser/ethereum/svm.py", line 10, in <module>
    from mythril.analysis.potential_issues import check_potential_issues
  File "/home/mythril/venv/lib/python3.9/site-packages/mythril/analysis/potential_issues.py", line 1, in <module>
    from mythril.analysis.report import Issue
  File "/home/mythril/venv/lib/python3.9/site-packages/mythril/analysis/report.py", line 12, in <module>
    from mythril.solidity.soliditycontract import SolidityContract
  File "/home/mythril/venv/lib/python3.9/site-packages/mythril/solidity/soliditycontract.py", line 7, in <module>
    from mythril.ethereum.evmcontract import EVMContract
  File "/home/mythril/venv/lib/python3.9/site-packages/mythril/ethereum/evmcontract.py", line 8, in <module>
    from mythril.disassembler.disassembly import Disassembly
  File "/home/mythril/venv/lib/python3.9/site-packages/mythril/disassembler/disassembly.py", line 2, in <module>
    from mythril.ethereum import util
  File "/home/mythril/venv/lib/python3.9/site-packages/mythril/ethereum/util.py", line 139, in <module>
    all_versions = solcx.get_installable_solc_versions()
  File "/home/mythril/venv/lib/python3.9/site-packages/solcx/install.py", line 322, in get_installable_solc_versions
    data = requests.get(BINARY_DOWNLOAD_BASE.format(_get_os_name(), "list.json"))
  File "/home/mythril/venv/lib/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/mythril/venv/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/mythril/venv/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/mythril/venv/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/mythril/venv/lib/python3.9/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='solc-bin.ethereum.org', port=443): Max retries exceeded with url: /linux-amd64/list.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbfba1de490>: Failed to establish a new connection: [Errno -2] Name or service not known'))
or('<urllib3.connection.HTTPSConnection object at 0x7fbfba1de490>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

## Expected behavior

Without internet, Mythril should try to continue with the compilers available. 

## Environment

- Mythril version: `v0.23.8`
- Python version: `3.9.14`
- OS and Version: Linux  Ubuntu 18.04.6

## Possible fix

```diff
diff --git a/mythril/ethereum/util.py b/mythril/ethereum/util.py
index 7b25246e..689207cf 100644
--- a/mythril/ethereum/util.py
+++ b/mythril/ethereum/util.py
@@ -138,8 +138,11 @@ def solc_exists(version):
     solc_binary = solcx.install.get_executable()
     return solc_binary
 
-
-all_versions = solcx.get_installable_solc_versions()
+try:
+    all_versions = solcx.get_installable_solc_versions()
+except:
+    # No internet, trying to proceed with installed compilers
+    all_versions = solcx.get_installed_solc_versions()
 
 
 def extract_version(file: str) -> Optional[str]:
```

**Comment by gsalzer** [comment]
Actually, it would be even better to delay the download of the list of available compilers to the point where Mythril discovers that it really needs a compiler that is not available locally.

Consider a framework like [SmartBugs](https://github.com/smartbugs/smartbugs), where a dockerized Mythril may be (and has been) run on several 100,000 contracts. A new container is created for every contract, meaning that the list of available compilers is downloaded several 100,000 times without being needed. When running Mythril with source code, SmartBugs takes care to provide the correct compiler within a mounted volume, otherwise Mythril would also download the compiler as many times, as any cached versions are discarded with the container. Making Mythril not download the list, though, is harder to achieve from the outside. Therefore it would help if Mythril avoided unnecessary internet connections and downloads by itself.

If you are basically willing to adapt Mythril, I can suggest a patch.

**Comment by norhh** [comment]
`
Consider a framework like [SmartBugs](https://github.com/smartbugs/smartbugs), where a dockerized Mythril may be (and has been) run on several 100,000 contracts. A new container is created for every contract, meaning that the list of available compilers is downloaded several 100,000 times without being needed. When running Mythril with source code, SmartBugs takes care to provide the correct compiler within a mounted volume, otherwise Mythril would also download the compiler as many times, as any cached versions are discarded with the container. Making Mythril not download the list, though, is harder to achieve from the outside. Therefore it would help if Mythril avoided unnecessary internet connections and downloads by itself.
`
One better way is to download all the solc versions in the docker container. I'll release a new docker version of mythril that can do that. This has to be done since docker contains only the latest solc version which might not be able to run many programs in a dataset.

`If you are basically willing to adapt Mythril, I can suggest a patch.`
Sure! That would be helpful.

**Comment by gsalzer** [comment]
> One better way is to download all the solc versions in the docker container. I'll release a new docker version of mythril that can do that. This has to be done since docker contains only the latest solc version which might not be able to run many programs in a dataset.

We considered to do this when dockerizing some analysis tools. Disadvantages:
- The images get obsolete when new solc versions are released, and would have to be rebuilt. This may not be a problem with a maintained tool like Mythril (except if someone wants to compare different dockerized verions of Mythril, with one image containing less solc versions than the other), but rebuilding is infeasible for a collection of unmaintained tools (it's already enough work to dockerize them once).
- The size of the image increases.

Therefore we determine the version of solc required by the solidity file outside of the docker container, fetch it if not yet cached, and copy it to a volume that is mounted inside the Docker container. This way even tools not configured to download solc by themselves are able to handle arbitrary solc versions, and the images don't get obsolete with new solc versions.
For this to work, I had to [extend `solcx` such that it downloads compilers cross-platform](https://github.com/smartbugs/py-solc-x): Even when running the framework on MacOS or Windows, it will download Linux binaries of solc, as needed by the Docker images.
