### ISSUE TITLE
Not compatible with python3.11 - Traceback (most recent call last):   File "/Library/Frameworks/Python.framework/Versions/3.11/bin/myth", line 5, in <module>     from mythril.interfaces.cli import main

### ISSUE THREAD

**Issue by alyyashar** [ConsenSysDiligence/mythril#1769]
When running
$myth 

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/myth", line 5, in <module>
    from mythril.interfaces.cli import main
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mythril/__init__.py", line 8, in <module>
    from mythril.plugin.loader import MythrilPluginLoader
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mythril/plugin/__init__.py", line 1, in <module>
    from mythril.plugin.interface import MythrilPlugin, MythrilCLIPlugin
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mythril/plugin/interface.py", line 2, in <module>
    from mythril.laser.plugin.builder import PluginBuilder as LaserPluginBuilder
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mythril/laser/plugin/builder.py", line 1, in <module>
    from mythril.laser.plugin.interface import LaserPlugin
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mythril/laser/plugin/interface.py", line 1, in <module>
    from mythril.laser.ethereum.svm import LaserEVM
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mythril/laser/ethereum/svm.py", line 10, in <module>
    from mythril.analysis.potential_issues import check_potential_issues
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mythril/analysis/potential_issues.py", line 1, in <module>
    from mythril.analysis.report import Issue
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mythril/analysis/report.py", line 6, in <module>
    from eth_abi import decode_abi
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/eth_abi/__init__.py", line 6, in <module>
    from eth_abi.abi import (  # NOQA
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/eth_abi/abi.py", line 1, in <module>
    from eth_abi.codec import (
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/eth_abi/codec.py", line 16, in <module>
    from eth_abi.decoding import (
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/eth_abi/decoding.py", line 14, in <module>
    from eth_abi.base import (
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/eth_abi/base.py", line 7, in <module>
    from .grammar import (
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/eth_abi/grammar.py", line 4, in <module>
    import parsimonious
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/parsimonious/__init__.py", line 9, in <module>
    from parsimonious.grammar import Grammar, TokenGrammar
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/parsimonious/grammar.py", line 14, in <module>
    from parsimonious.expressions import (Literal, Regex, Sequence, OneOf,
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/parsimonious/expressions.py", line 9, in <module>
    from inspect import getargspec
ImportError: cannot import name 'getargspec' from 'inspect' (/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/inspect.py)



```

**Comment by norhh** [comment]
This is due to py-evm and its libraries not supporting python 3.11. You can meanwhile stick to python 3.6-3.9 or use the docker container.
