### ISSUE TITLE
Can't run analysis using Docker on M1 Mac

### ISSUE THREAD

**Issue by RilRil** [ConsenSysDiligence/mythril#1808]
## Description

Getting errors when trying to run analysis on a contract using docker on a m1 mac 

```
docker run -v $(pwd)/src:/src mythril/myth a /src/Test.sol
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
mythril.interfaces.cli [ERROR]: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/solcx/install.py", line 633, in _validate_installation
    installed_version = wrapper._get_solc_version(binary_path)
  File "/usr/local/lib/python3.10/site-packages/solcx/wrapper.py", line 17, in _get_solc_version
    stdout_data = subprocess.check_output([str(solc_binary), "--version"], encoding="utf8")
  File "/usr/local/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/mythril/.solcx/solc-v0.8.18', '--version']' returned non-zero exit status 255.
```

## How to Reproduce
I followed documentation on how to install using Docker 
then ran docker run -v $(pwd)/src:/src mythril/myth a /src/Test.sol

**Comment by Masakore** [comment]
@RilRil 
Maybe adding platform params like below could help. 

`docker run --platform linux/amd64 -v $(pwd)/src:/src mythril/myth a /src/Test.sol`

Source:
https://stackoverflow.com/questions/71040681/qemu-x86-64-could-not-open-lib64-ld-linux-x86-64-so-2-no-such-file-or-direc/73619224#73619224

**Comment by RilRil** [comment]
it worked thanks !
