### ISSUE TITLE
DeclarationError: Identifier already declared.

### ISSUE THREAD

**Issue by jasmeenPedalsup** [ConsenSysDiligence/mythril#1819]
While running ` myth analyze zoopadTokenFactory.sol --solc-json  solc.json` I am getting below error.

```
mythril.interfaces.cli [ERROR]: Solc experienced a fatal error.

DeclarationError: Identifier already declared.
  --> Mocks/babyToken.sol:10:1:
   |
10 | import "@openzeppelin/contracts/access/Ownable.sol";
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Note: The previous declaration is here:
  --> ../node_modules/@openzeppelin/contracts/utils//Context.sol:16:1:
   |
16 | abstract contract Context {
   | ^ (Relevant source part starts here and spans across multiple lines).
```

below is my solc.json file

```
{
  "remappings": [ 
    "@openzeppelin/contracts/token/ERC20/utils/=../node_modules/@openzeppelin/contracts/token/ERC20/utils/",
    "@@openzeppelin/contracts/token/ERC20/=../node_modules/@@openzeppelin/contracts/token/ERC20/",
    "@openzeppelin/contracts/security/=../node_modules/@openzeppelin/contracts/security/",
    "@openzeppelin/contracts/token/ERC20/=../node_modules/@openzeppelin/contracts/token/ERC20/", 
    "@uniswap/v2-periphery/contracts/interfaces/=../node_modules/@uniswap/v2-periphery/contracts/interfaces/",
    "@openzeppelin/contracts/utils=../node_modules/@openzeppelin/contracts/utils/",
    "@openzeppelin/contracts/proxy/=../node_modules/@openzeppelin/contracts/proxy/",
    "@uniswap/v2-core/contracts/interfaces/=../node_modules/@uniswap/v2-core/contracts/interfaces/",
    "@openzeppelin/contracts/token/ERC20/extensions/=../node_modules/@openzeppelin/contracts/token/ERC20/extensions/",
    "@openzeppelin/contracts-upgradeable/access/=../node_modules/@openzeppelin/contracts-upgradeable/access/",
    "@openzeppelin/contracts-upgradeable/token/ERC20/=../node_modules/@openzeppelin/contracts-upgradeable/token/ERC20/",
    "@openzeppelin/contracts/access/=../node_modules/@openzeppelin/contracts/access/"
  ],
  "optimizer": {
    "enabled": true
 
  }
}
```

**Comment by norhh** [comment]
can you try reducing collisions in remappings and retry? You can remap `@openzeppelin`  directly to `../node_modules/@openzeppelin/` or remap `@openzeppelin/contracts` to `../node_modules/@openzeppelin/contracts`

**Comment by jasmeenPedalsup** [comment]
@norhh I reduce collision in remappings and retry and it's working but now I am getting other error

```
{
  "remappings": [ 
    "@openzeppelin/=../node_modules/@openzeppelin/",
    "@uniswap/v2-periphery/contracts/interfaces/=../node_modules/@uniswap/v2-periphery/contracts/interfaces/",
    "@uniswap/v2-core/contracts/interfaces/=../node_modules/@uniswap/v2-core/contracts/interfaces/"
  ],
  "optimizer": {
    "enabled": true
 
  }
}
```

```
mythril.mythril.mythril_analyzer [CRITICAL]: Exception occurred, aborting analysis. Please report this issue to the Mythril GitHub page.
Traceback (most recent call last):
  File "/home/pedalsup/.local/lib/python3.10/site-packages/mythril/mythril/mythril_analyzer.py", line 151, in fire_lasers
    sym = SymExecWrapper(
  File "/home/pedalsup/.local/lib/python3.10/site-packages/mythril/analysis/symbolic.py", line 182, in __init__
    self.laser.sym_exec(
  File "/home/pedalsup/.local/lib/python3.10/site-packages/mythril/laser/ethereum/svm.py", line 206, in sym_exec
    self.execute_transactions(created_account.address)
  File "/home/pedalsup/.local/lib/python3.10/site-packages/mythril/laser/ethereum/svm.py", line 232, in execute_transactions
    self._execute_transactions_incremental(
  File "/home/pedalsup/.local/lib/python3.10/site-packages/mythril/laser/ethereum/svm.py", line 302, in _execute_transactions_incremental
    execute_message_call(self, address, func_hashes=func_hashes)
  File "/home/pedalsup/.local/lib/python3.10/site-packages/mythril/laser/ethereum/transaction/symbolic.py", line 151, in execute_message_call
    laser_evm.exec()
  File "/home/pedalsup/.local/lib/python3.10/site-packages/mythril/laser/ethereum/svm.py", line 344, in exec
    new_states, op_code = self.execute_state(global_state)
  File "/home/pedalsup/.local/lib/python3.10/site-packages/mythril/laser/ethereum/svm.py", line 445, in execute_state
    ).evaluate(global_state)
  File "/home/pedalsup/.local/lib/python3.10/site-packages/mythril/laser/ethereum/instructions.py", line 265, in evaluate
    result = instruction_mutator(global_state)
  File "/home/pedalsup/.local/lib/python3.10/site-packages/mythril/laser/ethereum/instructions.py", line 196, in wrapper
    new_global_states = self.call_on_state_copy(func, func_obj, global_state)
  File "/home/pedalsup/.local/lib/python3.10/site-packages/mythril/laser/ethereum/instructions.py", line 131, in call_on_state_copy
    return func(func_obj, global_state_copy)
  File "/home/pedalsup/.local/lib/python3.10/site-packages/mythril/laser/ethereum/instructions.py", line 1090, in codecopy_
    if code.startswith("0x"):
AttributeError: 'tuple' object has no attribute 'startswith'
```

**Comment by norhh** [comment]
can you run it with the develop version? You can install develop version by cloning it and doing either:
`python setup.py install`
or 
`pip install .`

**Comment by jasmeenPedalsup** [comment]
I am getitng below error while running python setup.py install

```
Installed /usr/local/lib/python3.10/dist-packages/mythril-0.24.1-py3.10.egg
Processing dependencies for mythril==0.24.1
error: eth-utils 2.3.0 is installed but eth-utils<2,>=1.3.0 is required by {'py-ecc'}
```

**Comment by norhh** [comment]
I'll look into the conflicts.
To temporarily circumvent this, can you try directly executing the mythril script, use `./myth` (or whatever path the cloned repo is e.g: `/path/myth`) over directly running the `myth` command

**Comment by norhh** [comment]
Alternatively, you can try v0.24.2

**Comment by jasmeenPedalsup** [comment]
@norhh Thanks for the help me.
now I am using bytecode to analyze contracts
`myth a --bin -f test.asm  >> outpuy2.json`

it will generate below output
```
==== State access after external call ====
SWC ID: 107
Severity: Low
Contract: MAIN
Function name: _function_0x92a13eda
PC address: 1167
Estimated Gas Usage: 24901 - 140223
Write to persistent state following external call
The contract account state is accessed after an external call to a fixed address. To prevent reentrancy issues, consider accessing the state only before the call, especially if the callee is untrusted. Alternatively, a reentrancy lock can be used to prevent untrusted callees from re-entering the contract in an intermediate state.
--------------------
Initial State:

Account: [ATTACKER], balance: 0x0, nonce:0, storage:{}
Account: [SOMEGUY], balance: 0x0, nonce:0, storage:{}

Transaction Sequence:

Caller: [CREATOR], function: unknown, txdata: 0x92a13ed 
```

can i get real function name from `_function_0x92a13eda`?

another question is Is mythril use slither internally or it is independent from slither?

**Comment by norhh** [comment]
It's independent of slither.
Bytecode does not have function information, you can get function-hash list by running `solc --hashes file.sol <a bunch of args for handling imports for remappings>` 
does v0.24.2 crash throw this crash? since I pushed some changes yesterday which shouldn't result in this crash
