### ISSUE TITLE
Mythril 0.24.4 raises an error on macOS

### ISSUE THREAD

**Issue by shikahJS** [ConsenSysDiligence/mythril#1829]
## Description

Running Mythril on macOS terminal always results in an error.

## How to Reproduce

I tried to run Mythril on the provided contracts sample using the following command:
$ myth analyze contract.sol

==== Exception state ===
The following error always appears:

mythril.interfaces.cli [ERROR]: Traceback (most recent call last):
  File "/Library/Python/3.9/site-packages/mythril-0.24.4-py3.9.egg/mythril/interfaces/cli.py", line 953, in parse_args_and_execute
    config = set_config(args)
  File "/Library/Python/3.9/site-packages/mythril-0.24.4-py3.9.egg/mythril/interfaces/cli.py", line 675, in set_config
    config = MythrilConfig()
  File "/Library/Python/3.9/site-packages/mythril-0.24.4-py3.9.egg/mythril/mythril/mythril_config.py", line 26, in __init__
    self.mythril_dir = self.init_mythril_dir()
  File "/Library/Python/3.9/site-packages/mythril-0.24.4-py3.9.egg/mythril/mythril/mythril_config.py", line 56, in init_mythril_dir
    copyfile(str(asset_dir / "signatures.db"), db_path)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
NotADirectoryError: [Errno 20] Not a directory: '/Library/Python/3.9/site-packages/mythril-0.24.4-py3.9.egg/mythril/support/assets/signatures.db'

## Expected behavior

Getting the analysis result

## Environment

- Mythril version: v0.24.4
- Solidity compiler and version: 0.8.23+commit.f704f362.Darwin.appleclang
- Python version: Python 3.9.6
- OS and Version: Mac OS Sonoma

Can you please explain how this error can be solved.

Thanks for helping!

**Comment by norhh** [comment]
Hi, This should be an issue with the recent mac version.
Can you try running it on docker while I fix this?

**Comment by norhh** [comment]
This should've been fixed in the recent version
